### ISSUE TITLE
Weird comments in Java files

### ISSUE THREAD

**Issue by rmcloughlin** [akka/akka-quickstart-java.g8#15]
Printer.java has this comment repeated six times:

`//#printer-messages`

What is this for?  Greeter.java is similar.

**Comment by ktoso** [comment]
This is in order to power the snippet inclusion on the documentation page: http://developer.lightbend.com/guides/akka-quickstart-java/create-actors.html

Snippets can be included by using those names so one does not include the entire file, but only sections demarkated by the `//#printer-messages` etc comments.

Hope this clarifies things!

**Comment by ktoso** [comment]
Example here: https://github.com/akka/akka-quickstart-java.g8/blob/2.5.x/docs/src/main/paradox/communicate-with-actors.md

Feel free to ignore these, and we recommend reading the docs as you learn here, and then look at the full sources - ignore these comments there. 

Cheers, I'll close the ticket - hope this clarified things a bit
